/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
 */

#import "CoreTelephony-Structs.h"
#import <Foundation/NSObject.h>

@class NSString;

@interface CTCall : NSObject {
@private
	NSString* _callState;
	NSString* _callID;
}
@property(copy, nonatomic) NSString* callID;
@property(copy, nonatomic) NSString* callState;
+(id)callForCTCallRef:(CTCallRef)ctcallRef;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(id)description;
-(void)dealloc;
@end

