/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
 */

#import <Foundation/NSObject.h>

@class NSSet;

@interface CTCallCenter : NSObject {
@private
	void* _internal;
	NSSet* _currentCalls;
	id _callEventHandler;
}
@property(copy, nonatomic) id callEventHandler;
@property(retain) NSSet* currentCalls;
-(id)description;
-(void)broadcastCallStateChangesIfNeededWithFailureLogMessage:(id)failureLogMessage;
-(void)handleNotificationFromConnection:(void*)connection ofType:(id)type withInfo:(id)info;
-(BOOL)calculateCallStateChanges:(id)changes;
-(BOOL)getCurrentCallSetFromServer:(id)server;
-(void)dealloc;
-(id)init;
-(void)cleanUpServerConnection;
-(void)cleanUpServerConnectionNoLock;
-(void)reestablishServerConnectionIfNeeded;
-(BOOL)setUpServerConnection;
@end

