/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
 */

#import <Foundation/NSObject.h>

@class NSString;

@interface CTCarrier : NSObject {
	NSString* _carrierName;
	NSString* _mobileCountryCode;
	NSString* _mobileNetworkCode;
	NSString* _isoCountryCode;
	BOOL _allowsVOIP;
}
@property(assign, nonatomic) BOOL allowsVOIP;
@property(retain, nonatomic) NSString* isoCountryCode;
@property(retain, nonatomic) NSString* mobileNetworkCode;
@property(retain, nonatomic) NSString* mobileCountryCode;
@property(retain, nonatomic) NSString* carrierName;
-(BOOL)isEqual:(id)equal;
-(void)dealloc;
-(id)init;
-(id)description;
@end

