/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
 */

#import "NSCopying.h"
#import "CTMessageAddress.h"
#import "CoreTelephony-Structs.h"
#import <Foundation/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface CTEmailAddress : NSObject <NSCopying, CTMessageAddress> {
@private
	NSString* _address;
}
@property(readonly, assign) NSString* address;
+(id)emailAddress:(id)address;
-(id)canonicalFormat;
-(id)encodedString;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
-(id)initWithAddress:(id)address;
@end

