/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
 */

#import <Foundation/NSObject.h>

@class NSData, NSString, NSMutableDictionary;

@interface CTMessagePart : NSObject {
	NSString* _contentType;
	NSMutableDictionary* _contentTypeParams;
	NSString* _contentId;
	NSString* _contentLocation;
	NSData* _data;
}
@property(copy, nonatomic) NSData* data;
@property(copy, nonatomic) NSString* contentLocation;
@property(copy, nonatomic) NSString* contentId;
@property(copy, nonatomic) NSString* contentType;
-(void)dealloc;
-(id)allContentTypeParameterNames;
-(void)addContentTypeParameterWithName:(id)name value:(id)value;
-(id)contentTypeParameterWithName:(id)name;
-(id)initWithData:(id)data contentType:(id)type;
@end

