/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
 */

#import "CoreTelephony-Structs.h"
#import <Foundation/NSObject.h>


@interface CTMessageCenter : NSObject {
}
+(id)sharedMessageCenter;
-(BOOL)getCharacterCount:(int*)count andMessageSplitThreshold:(int*)threshold forSmsText:(id)smsText;
-(BOOL)sendSMSWithText:(id)text serviceCenter:(id)center toAddress:(id)address withMoreToFollow:(BOOL)follow;
-(BOOL)sendSMSWithText:(id)text serviceCenter:(id)center toAddress:(id)address;
-(BOOL)isMmsConfigured;
-(BOOL)isMmsEnabled;
-(void)setDeliveryReportsEnabled:(BOOL)enabled;
-(XXStruct_K5nmsA)isDeliveryReportsEnabled:(BOOL*)enabled;
-(id)decodeMessage:(id)message;
-(id)encodeMessage:(id)message;
-(id)statusOfOutgoingMessages;
-(id)deferredMessageWithId:(unsigned)anId;
-(id)incomingMessageWithId:(unsigned)anId;
-(void)acknowledgeOutgoingMessageWithId:(unsigned)anId;
-(void)acknowledgeIncomingMessageWithId:(unsigned)anId;
-(id)allIncomingMessages;
-(int)incomingMessageCount;
-(id)incomingMessageWithId:(unsigned)anId telephonyCenter:(CTTelephonyCenterRef)center isDeferred:(BOOL)deferred;
-(XXStruct_K5nmsA)send:(id)send withMoreToFollow:(BOOL)follow;
-(XXStruct_K5nmsA)send:(id)send;
-(XXStruct_K5nmsA)sendMMS:(id)mms;
-(void)sendMessageAsSmsToShortCodeRecipients:(id)shortCodeRecipients andReplaceData:(id*)data;
-(XXStruct_K5nmsA)sendMMSFromData:(id)data messageId:(unsigned)anId;
-(XXStruct_K5nmsA)sendSMS:(id)sms withMoreToFollow:(BOOL)follow;
-(id)init;
@end

