/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
 */

#import <Foundation/NSObject.h>

@class NSDictionary, NSDate, NSString, NSMutableDictionary, NSArray, CTPhoneNumber, NSMutableArray;
@protocol NSCopying, CTMessageAddress;

@interface CTMessage : NSObject {
	NSObject<NSCopying, CTMessageAddress>* _sender;
	NSMutableArray* _recipients;
	NSMutableArray* _items;
	NSDictionary* _rawHeaders;
	NSDate* _date;
	unsigned _messageId;
	int _messageType;
	CTPhoneNumber* _serviceCenter;
	NSString* _subject;
	NSString* _contentType;
	NSMutableDictionary* _contentTypeParams;
	unsigned _replaceMessage;
	NSString* _countryCode;
}
@property(readonly, assign, nonatomic) NSString* countryCode;
@property(copy, nonatomic) NSString* contentType;
@property(copy, nonatomic) NSObject<NSCopying, CTMessageAddress>* sender;
@property(copy, nonatomic) NSString* subject;
@property(copy, nonatomic) CTPhoneNumber* serviceCenter;
@property(assign, nonatomic) int messageType;
@property(assign, nonatomic) unsigned messageId;
@property(readonly, assign) unsigned replaceMessage;
@property(readonly, assign) NSDictionary* rawHeaders;
@property(readonly, assign) NSArray* items;
@property(readonly, assign) NSDate* date;
@property(readonly, assign) NSArray* recipients;
-(void)setCountryCode:(id)code;
-(id)description;
-(id)allContentTypeParameterNames;
-(void)addContentTypeParameterWithName:(id)name value:(id)value;
-(id)contentTypeParameterWithName:(id)name;
-(void)removePartAtIndex:(unsigned)index;
-(id)addPart:(id)part;
-(id)addData:(id)data withContentType:(id)contentType;
-(id)addText:(id)text;
-(void)addEmailRecipient:(id)recipient;
-(void)addPhoneRecipient:(id)recipient;
-(void)setRecipients:(id)recipients;
-(void)setRecipient:(id)recipient;
-(void)removeRecipientsInArray:(id)array;
-(void)removeRecipient:(id)recipient;
-(void)addRecipient:(id)recipient;
-(void)setReplaceMessage:(unsigned)message;
-(void)setRawHeaders:(id)headers;
-(void)dealloc;
-(id)initWithDate:(id)date;
-(id)init;
@end

