/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
 */

#import <Foundation/NSObject.h>


@interface CTMessageStatus : NSObject {
	unsigned _messageId;
	int _messageType;
	int _result;
}
@property(readonly, assign) int result;
@property(readonly, assign) int messageType;
@property(readonly, assign) unsigned messageId;
-(id)initWithMessageId:(unsigned)messageId messageType:(int)type result:(int)result;
@end

