/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
 */

#import "NSCopying.h"
#import "CTMessageAddress.h"
#import "CoreTelephony-Structs.h"
#import <Foundation/NSObject.h>

@class NSString;

@interface CTPhoneNumber : NSObject <NSCopying, CTMessageAddress> {
	NSString* _digits;
	NSString* _countryCode;
	BOOL _isShortCode;
}
@property(assign) BOOL isShortCode;
@property(readonly, assign) NSString* countryCode;
@property(readonly, assign) NSString* digits;
+(id)phoneNumberWithDigits:(id)digits countryCode:(id)code;
-(id)encodedString;
-(id)canonicalFormat;
-(id)formatForCallingCountry:(id)callingCountry;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
-(id)initWithDigits:(id)digits countryCode:(id)code;
-(int)numberOfDigitsForShortCodeNumber;
@end

