/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
 */

#import "CoreTelephony-Structs.h"
#import <Foundation/NSObject.h>

@class CTCarrier;

@interface CTTelephonyNetworkInfo : NSObject {
@private
	void* _internal;
	CTCarrier* _subscriberCellularProvider;
	id _subscriberCellularProviderDidUpdateNotifier;
}
@property(copy, nonatomic) id subscriberCellularProviderDidUpdateNotifier;
@property(retain) CTCarrier* subscriberCellularProvider;
-(void)postUpdatesIfNecessary;
-(void)handleNotificationFromConnection:(void*)connection ofType:(id)type withInfo:(id)info;
-(BOOL)updateNetworkInfoAndShouldNotifyClient:(BOOL*)updateNetworkInfoAnd;
-(BOOL)getAllowsVOIP:(BOOL*)voip withCTError:(XXStruct_K5nmsA*)cterror;
-(BOOL)getMobileNetworkCode:(id)code withCTError:(XXStruct_K5nmsA*)cterror;
-(BOOL)getMobileCountryCode:(id)code andIsoCountryCode:(id)code2 withCTError:(XXStruct_K5nmsA*)cterror;
-(BOOL)getCarrierName:(id)name withCTError:(XXStruct_K5nmsA*)cterror;
-(void)dealloc;
-(id)init;
-(void)cleanUpServerConnection;
-(void)cleanUpServerConnectionNoLock;
-(void)reestablishServerConnectionIfNeeded;
-(BOOL)setUpServerConnection;
@end

